const data = [
	{
		id: "1",
		images: ["./assets/card.svg", "./assets/card.svg", "./assets/card.svg"],
		rating: 4.5,
		title: "Sea La Vie",
		reviews: "105 reviews",
		price: "1,42,726",
	},
	{
		id: "2",
		images: ["./assets/card.svg", "./assets/card.svg", "./assets/card.svg"],
		rating: 4.2,
		title: "Sea Laas Vie",
		reviews: "100 reviews",
		price: "1,10,726",
	},
	{
		id: "3",
		images: ["./assets/card.svg", "./assets/card.svg", "./assets/card.svg"],
		rating: 3.5,
		title: "Fred- The weekend Home",
		reviews: "109 reviews",
		price: "2,42,726",
	},
	{
		id: "4",
		images: ["./assets/card.svg", "./assets/card.svg", "./assets/card.svg"],
		rating: 4.5,
		title: "Sea La Vie",
		reviews: "105 reviews",
		price: "1,00,726",
	},
	{
		id: "5",
		images: ["./assets/card.svg", "./assets/card.svg", "./assets/card.svg"],
		rating: 4.5,
		title: "Sea La Vie",
		reviews: "105 reviews",
		price: "1,28,124",
	},
	{
		id: "6",
		images: ["./assets/card.svg", "./assets/card.svg", "./assets/card.svg"],
		rating: 3.5,
		title: "Sea La Vie",
		reviews: "90 reviews",
		price: "1,42,726",
	},
	{
		id: "7",
		images: ["./assets/card.svg", "./assets/card.svg", "./assets/card.svg"],
		rating: 4.5,
		title: "Sea La Vie",
		reviews: "105 reviews",
		price: "1,42,324",
	},
	{
		id: "8",
		images: ["./assets/card.svg", "./assets/card.svg", "./assets/card.svg"],
		rating: 4.5,
		title: "Sea La Vie",
		reviews: "105 reviews",
		price: "1,45,726",
	},
	{
		id: "9",
		images: ["./assets/card.svg", "./assets/card.svg", "./assets/card.svg"],
		rating: 4.5,
		title: "Sea La Vie",
		reviews: "105 reviews",
		price: "1,13,726",
	},
	{
		id: "10",
		images: ["./assets/card.svg", "./assets/card.svg", "./assets/card.svg"],
		rating: 4.5,
		title: "Sea La Vie",
		reviews: "105 reviews",
		price: "1,42,726",
	},
	{
		id: "11",
		images: ["./assets/card.svg", "./assets/card.svg", "./assets/card.svg"],
		rating: 4.5,
		title: "Sea La Vie",
		reviews: "105 reviews",
		price: "1,84,726",
	},
	{
		id: "12",
		images: ["./assets/card.svg", "./assets/card.svg", "./assets/card.svg"],
		rating: 4.5,
		title: "Sea La Vie",
		reviews: "105 reviews",
		price: "1,42,726",
	},
];

export default data;
